### ISSUE TITLE
get streaming link not working.

### ISSUE THREAD

**Issue by azimkhan0** [codex0555/Aniwatch-Api#1]
this is't providing any streaming links when i tried to get. 
it's just showing the available servers. 
![image](https://github.com/codex0555/Aniwatch-Api/assets/145858485/6f59a3fc-1501-474d-9ecd-9b7db00a73bd)

**Comment by codex0555** [comment]
the link is in server-src

**Comment by azimkhan0** [comment]
> the link is in server-src

i'm using the method that you've used in the doccumentation. 
https://aniwatch-api-v1-0.onrender.com/api/server/[srcId]

but it's showing the available server list. though the api endpoint for getting the server list was.
https://aniwatch-api-v1-0.onrender.com/api/server/id=[episode Id]

please tell me how can i get the links for streaming or is it a bug in the api?

**Comment by codex0555** [comment]
/spi/server-src/src_id

**Comment by apurvsikka** [comment]
the url for aniwatch.to has now changed to ['https://hianime.to'](url)

**Comment by codex0555** [comment]
We will fix

**Comment by codex0555** [comment]
> the url for aniwatch.to has now changed to https://hianime.to

We will fix thanks for the comment
